export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_HEADING = 'UPDATE_HEADING';
export const UPDATE_DESCRIPTION = 'UPDATE_DESCRIPTION';
export const UPDATE_TAGS = 'UPDATE_TAGS';
export const UPDATE_READING_TIME = 'UPDATE_READING_TIME';
export const UPDATE_PUBLISHER_NAME = 'UPDATE_PUBLISHER_NAME';
